### PR TITLE
Fix display of testing page

### PR DESCRIPTION
**Pull request by pletelli**
The goal of this PR is to upgrade to Framework7 version 2.0.

### CODE REVIEW

**Comment by ChloeEmmaA** [comment]
👍

**Comment by Olivier0** [comment]
It still seems broken: https://rawgit.com/ChloeEmmaA/open-sympto/fix_rawgit/web/app.html

I believe the simplest way is to restart from the template at https://github.com/framework7io/framework7-template-tabs and copy/paste our existing content in there.

**Comment by Olivier0** [comment]
The default appearance of framwork7 version 2 is quite different from version 1.6 we used previously. I tried to get as close as possible to what we had with version 1.6. However, I feel the page where we input the observations doesn't look as nice as before (I just copied/pasted it, didn't try to make it nice), but it should be easy to improve it. I also committed the framework7 2.0 files in our repository so that we don't experience upgrade problems any more. If you agree we could merge this PR and continue on the top of this instead of version 1.6.

You can view the result here: https://rawgit.com/ChloeEmmaA/open-sympto/fix_rawgit/web/app.html

👍

**Comment by ChloeEmmaA** [comment]
@Olivier0 , I don't understand, because I think that you didn't start from the master branch. In the master branch version, there are 5 tabs, and already the graph in the cycle tab...

**Comment by Olivier0** [comment]
No, I had to restart from scratch as there are too many differences between Framework7 version 1.6 and 2.0. However re-adding the missing tabs should be a child's play.

Note that I have some doubts about the calendar tab. I believe we could merge the calendar tab with the cycle tab by adding one or two rows at the top of cycle table indicating the month and the day of the month. What do you think?

Since it is easy to add a tab, I would suggest that we don't add empty tabs, but we add tab only when we have the content of a tab. For example, in version 1.0 of open-sympto, we won't implement the chat, so it would be better not to have an empty chat tab. Isn't it?

**Comment by ChloeEmmaA** [comment]
👍 Ok! You can merge, then I will add what is missing (and that was already in the old version) and needed for V1.

**Comment by pletelli** [comment]
was ok to me !

**Comment by pletelli** [comment]
agree with @Olivier0: we shouldn't have an empty tab for something we will implement later

**Pull request merged**
