### PR TITLE
Linting and style check

### PR DESCRIPTION
**Pull request by pletelli**
Linting and style is fundamental to save time when working in teams on the same files (no need to distrust for typos and formatting issues), plus it helps for the readability.
I suggest we follow the rules of ESLint : https://eslint.org/docs/rules/

I'm currently working on finding CI tools to automate the checking of linting rules and style, that's why this PR is a WIP
The chosen CI service will have to be set up through "Settings" -> "Integration and services".

### CODE REVIEW

**Comment by Olivier0** [comment]
Note: I usually consider all PRs as WIP until the author of the PR issues a comment with a thumb up (👍) which means the PR is complete and ready for review.

**Comment by Olivier0** [comment]
I installed ESlint-linter package in my [atom](https://atom.io) source code editor and configured it with a standard configuration (which I just committed on this PR).

**Comment by Olivier0** [comment]
Now, I am trying to use the `beautify` package for atom to fix the style of HTML files...

**Comment by Olivier0** [comment]
I am done with this PR.

To be compliant with our coding style, you should use [atom](the https://atom.io) text editor and install the `atom-beautify` and `linter-eslint` packages that will use the two configurations files I commited on this PR (respectively `.jsbeautifyrc` and `.eslintrc.json` to check the coding style and lint your code.

Note: it may be convenient to enable the "beautify on save" feature of the `atom-beautify` package.

In a second step we could add some CI tools (based on github hooks with travis or other service) that will check the coding style and linting. But I would suggest that we already merge this PR now to ensure we start using the linter and coding style defined here (and possible open a new one for setting up the CI tools).

**Comment by Olivier0** [comment]
I just tested it at https://rawgit.com/ChloeEmmaA/open-sympto/linting_and_style/web/app.html and it seems this PR doesn't break our app 😉.

👍

**Comment by ChloeEmmaA** [comment]
👍

**Pull request merged**
