### PR TITLE
Updated README with technical information (restored PR)

### PR DESCRIPTION
**Pull request by omichel**
I just restored the PR #2 here which was merged by @ChloeEmmaA.

### CODE REVIEW

**Comment by omichel** [comment]
You can either make direct contributions by editing the README.md file on this PR or write comment on the discussion thread of this PR. I will merge it only after I get the approval of at least two reviewers.

👍 (that means the PR is ready for review)

**Comment by pletelli** [comment]
Comment from @ChloeEmmaA , that I have deleted from the README : I would reuse the terminology but not the icons, we can use similar ones but I think that it is better to create our own icons so that users make the difference between the two apps.

My own comments are:
* I aggree with @ChloeEmmaA 's argument, plus I'm not fond of sympto's icons because they look outdated to me.
* I'm not sure we should already specify in our `Requirements`, it seems to me that they are really long term goals:
~~~md
- allow to chat with other users.
- allow to be connected to a consellor from the Symptotherm fundation.
~~~
Is it really something we want from the app that is fundation independant ?

**Comment by omichel** [comment]
Because @ChloeEmmaA agreed on slack about postponing the question of implementing the chat and conseilling services, I marked those items as "to be rediscussed later" and moved them at the end of list.

👍

**Comment by omichel** [comment]
(Note: the 👍 I just posted means that I am now waiting for your reviews. If you both approve, e.g., from the "Files changes" &rarr; "Review changes" &rarr; "Approve", I will merge this PR in the master branch, otherwise the discussion will continue until we all agree.)

**Comment by omichel** [comment]
Note: If @pletelli don't approve this PR until tonight, it would be simpler that @ChloeEmmaA writes her contribution directly into this PR. Otherwise, if @pletelli approves this PR, I will merge it in the master branch and @ChloeEmmaA could create a new PR from the master branch for her new contribution proposal.

**Comment by pletelli** [comment]
Good for me in this state. 👍 I'm merging

**Comment by omichel** [comment]
Thank you. Done.

**Pull request merged**
