### PR TITLE
Added demo tab bar application from Framework7

### PR DESCRIPTION
**Pull request by Olivier0**
This is the demo Tab Bar Application of Framework 7 taken from here: https://framework7.io/examples/
I believe the tab structure is something close to what we want to achieve. Also several widgets are interesting are we could reuse them in our app.

You can view it here: https://htmlpreview.github.io/?https://github.com/ChloeEmmaA/open-sympto/feature-demo-page/web/app.html

The next steps will be to modify its content so that it maches our need for open-sympto and we can complete https://github.com/ChloeEmmaA/open-sympto/milestone/2

### CODE REVIEW

**Comment by Olivier0** [comment]
👍

**Comment by ChloeEmmaA** [comment]
I started to modify the content of the tabs in another branch and made a pull request to merge with this one (feature-demo-page).

**Comment by Olivier0** [comment]
👎 It seems the tabs don't work properly and I get this error in the Javascript console:
```javascript
SyntaxError: '//htmlpreview.github.io/?https://raw.githubusercontent.com/ChloeEmmaA/open-sympto/feature-demo-page/web/app/index.html#view-2' is not a valid selector
framework7.js:15
```
I am investigating how to fix that. 😕

**Comment by Olivier0** [comment]
I just found the solution: use a better web service for that: https://rawgit.com/ChloeEmmaA/open-sympto/feature-demo-page/web/app.html
That works nicely for me. :smile:

**Comment by Olivier0** [comment]
:+1:

**Pull request merged**
