### PR TITLE
many changes

### PR DESCRIPTION
**Pull request by ChloeEmmaA**
prepare the saving variables, add the content in the method tab, add a plus button, change color to green, change tab icon.

### CODE REVIEW

**Comment by Olivier0** [comment]
:eyes:

**Comment by Olivier0** [comment]
It seems there are way too many files committed in this PR. We normally need only a subset of the icon library you included. See the simple copy instructions here: https://github.com/ChloeEmmaA/open-sympto/blob/4384daf0110d0c91863678bd13fe659af4d1b123/web/app/framework7-icons-master/README.md (and this file is not needed either).

**Comment by Olivier0** [comment]
Test link: https://rawgit.com/ChloeEmmaA/open-sympto/add_features/web/app.html
Congratulation @ChloeEmmaA, it looks very good. You did an excellent job!
Do you want me to cleanup the unnecessary icon library files?

**Comment by Olivier0** [comment]
Ok, this is all right for me now to merge this PR. Once merged, I will open a new PR aiming at storing and retrieving the data in the database and updating the graph accordingly.

**Comment by pletelli** [comment]
Wow, this is great. I'm also eager to do work with the data !

**Pull request merged**
